/*
 * This source file was generated by the Gradle 'init' task
 */
package genshinimpactswing;

import javax.swing.*;

import java.awt.*;

public class App extends JFrame {

    public App(){
        setTitle("GenshinImpactWiki");
        setSize(1200,700);
        setLocationRelativeTo(null);
        setUndecorated(true);

        TopPanel topPanel = new TopPanel();
        add(topPanel, BorderLayout.NORTH);

        MainView mainView = new MainView();
        add(mainView, BorderLayout.CENTER);

        ResizeListener resizeListener = new ResizeListener(this);
        addMouseListener(resizeListener);
        addMouseMotionListener(resizeListener);
    }

    

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().setVisible(true);
        });
    }
}
